import { ClientPacket } from "../ClientPacket.ts";

/**
 * Used to send a chat message to the server.
 *
 * @see {@link https://minecraft.wiki/w/Java_Edition_protocol/Packets#Chat_Message|Chat Message}
 */
export class Chat extends ClientPacket {
  public static override readonly ID = 0x08;

  /**
   * @param message Content of the message. May not be longer than 256 characters,
   *    or else the server will kick the client.
   * @param timestamp Timestamp of the message.
   * @param salt The salt used to verify the signature hash. Randomly generated by the client.
   * @param signature The signature used to verify the chat message's authentication.
   * @param count Number of signed clientbound chat messages the client has seen from the server since the last
   *    serverbound chat message from this client.
   * @param acknowledged Bitmask of which message signatures from the last seen set were used to sign this message.
   * @param checksum Checksum is computed over all the message signature checksums in the last seen set,
   *    from oldest to newest.
   */
  public constructor(
    message: string,
    timestamp: bigint,
    salt: bigint,
    signature: Uint8Array<ArrayBuffer> | null,
    count: number,
    acknowledged: number | bigint,
    checksum: number,
  ) {
    super();
    this.writeString(message);
    this.writeLong(timestamp);
    this.writeLong(salt);
    this.writeOptional(signature, this.writeByteArray);
    this.writeVarInt(count);
    this.writeFixedBitSet(BigInt(acknowledged), 20);
    this.writeByte(checksum);
  }
}
