import { ServerPacket } from "../ServerPacket.ts";
import { State } from "../../State.ts";

/**
 * Encryption Request
 *
 * @see {@link https://minecraft.wiki/w/Java_Edition_protocol/Packets#Encryption_Request|Encryption Request}}
 * @see {@link https://minecraft.wiki/w/Protocol_encryption|Protocol encryption}
 */
export class Hello extends ServerPacket {
  public static override readonly ID = 0x01;
  public static override readonly STATE = State.LOGIN;

  /**
   * Always empty when sent by the vanilla server.
   */
  public readonly serverId: string;

  /**
   * The server's public key.
   */
  public readonly publicKey: Uint8Array<ArrayBuffer>;

  /**
   * A sequence of random bytes generated by the server.
   */
  public readonly verifyToken: Uint8Array<ArrayBuffer>;

  /**
   * Whether the client should attempt to authenticate through Mojang servers.
   */
  public readonly shouldAuthenticate: boolean;

  public constructor(buf: Uint8Array<ArrayBuffer>) {
    super(buf);
    this.serverId = this.readString();
    this.publicKey = this.readByteArray();
    this.verifyToken = this.readByteArray();
    this.shouldAuthenticate = this.readBoolean();
  }
}
